---
title: "Tidy Data and Relational Datasets"
output: html_document
date: "2022-09-27"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## `pivot_longer`
```{r}
  pulse_df = haven::read_sas('data/public_pulse_data.sas7bdat') %>%
    janitor::clean_names() %>%
    pivot_longer(
      bdi_score_bl:bdi_score_12m,
      names_to = 'visit',
      values_to = 'bdi',
      names_prefix = 'bdi_score_'
    ) %>%
    mutate(
      visit = replace(visit, visit == 'bl', '00m'),
      visit = factor(visit)
    ) %>%
    arrange (id, visit)
```

### Learning Assessment 
```{r}
litters_df = read_csv('data/FAS_litters.csv') %>%
    janitor::clean_names() %>%
    select(litter_number, ends_with('weight')) %>%
    pivot_longer(
      gd0_weight:gd18_weight,
      names_to = 'gd',
      values_to = 'weight',
    ) %>%
    mutate(
      gd = recode(gd, 'gd0_weight' = 0, 'gd18_weight' = 18)
    )
view(litters_df)
```

## `pivot_wider`
```{r}
  analysis_results = tibble(
    group = c('treatment', 'treatment', 'placebo', 'placebo'),
    time = c('pre', 'post', 'pre', 'post'),
    mean = c(4, 8, 3.5, 4)
  )

  analysis_results_wide = pivot_wider(
    analysis_results, 
    names_from = 'time',
    values_from = 'mean',
  )
```

## Binding Rows
```{r}
  fellowship_ring = readxl::read_excel('data/LotR_Words.xlsx', range = 'B3:D6') %>%
    mutate(movie = 'fellowship_ring')

  two_towers = readxl::read_excel('data/LotR_Words.xlsx', range = 'F3:H6') %>%
    mutate(movie = 'two_towers')
  
  return_king = readxl::read_excel('data/LotR_Words.xlsx', range = 'J3:L6') %>%
    mutate(movie = 'return_king')
  
  
  lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>%
    janitor::clean_names() %>%
    pivot_longer(
      female:male,
      names_to = 'gender',
      values_to = 'words',
    ) %>%
    mutate(race = str_to_lower(race))

```

## Joining Datasets

```{r}
  pups = 
    read_csv('data/FAS_pups.csv') %>%
    janitor::clean_names() %>%
    mutate(sex = recode(sex, '1' = 'male', '2' = 'female'))

  litter = 
    read_csv('data/FAS_litters.csv') %>%
    janitor::clean_names() %>%
    separate(group, into = c('dose', 'day_of_tx'), sep = 3) %>%
    mutate(
      wt_gain = gd18_weight - gd0_weight,
      dose = str_to_lower(dose)
    )
  
  fas_data = 
    left_join(pups, litter)
```

### Learning Assessment 
```{r}
surv_os = 
    read_csv('data/surv_os.csv') %>%
    janitor::clean_names() %>%
    rename(id = what_is_your_uni, os = what_operating_system_do_you_use)

surv_program = 
    read_csv('data/surv_program_git.csv') %>%
    janitor::clean_names() %>%
    rename(
      id = what_is_your_uni,
      prog = what_is_your_degree_program,
      git_exp = which_most_accurately_describes_your_experience_with_git
    )

left_join(surv_os, surv_program)
inner_join(surv_os, surv_program)
anti_join(surv_os, surv_program)
anti_join(surv_program, surv_os)
```



